# Generated by Django 4.1.2 on 2022-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(help_text='Введите имя пользователя', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию пользователя', max_length=50, verbose_name='Фамилия')),
                ('phone', models.CharField(help_text='Введите номер телефона', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Электронная почта')),
                ('role', models.CharField(choices=[('Пользователь', 'user'), ('Админ', 'admin')], default='user', max_length=12)),
                ('image', models.ImageField(upload_to='django_media/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
